project:
  type: default

format:
  pdf:
    pdf-engine: xelatex
    documentclass: kaohandt
    classoption: []
    lang: en
    keep-tex: true
    template: kao-template.tex
    template-partials:
      - pandoc.tex
      - tables.tex
    mainfont: "LibertinusSerif"
    mainfontoptions:
      - "Path=./fonts/"
      - "Extension=.otf"
      - "UprightFont=*-Regular"
      - "BoldFont=*-Bold"
      - "ItalicFont=*-Italic"
      - "BoldItalicFont=*-BoldItalic"
